apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: siren
data:
  elasticsearch.yml: |
    cluster.name: siren
    network.host: "0.0.0.0"
    bootstrap.memory_lock: false
    discovery.zen.ping.unicast.hosts:
    - es-discovery
    discovery.zen.minimum_master_nodes: 3