apiVersion: zalando.org/v1
kind: ElasticsearchDataSet
metadata:
  labels:
    application: es
    role: data
  name: es-data
  namespace: siren
spec:
  replicas: {{ .Env.NODES }}
  scaling:
    enabled: false
  template:
    metadata:
      labels:
        application: es
        role: data
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: component
                  operator: In
                  values:
                  - elasticsearch
                - key: role
                  operator: In
                  values:
                  - data
              topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 50m
        securityContext:
          privileged: true
      - name: config
        image: busybox
        command:
        - "sh"
        - "-c"
        - "elasticsearch-keystore create && elasticsearch-keystore add-file gcs.client.default.credentials_file /gcloud-secrets/account.json && cp config/elasticsearch.keystore /keystore/elasticsearch.keystore && chmod a+rwx /keystore/elasticsearch.keystore"
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - name: es-keystore
          mountPath: /keystore
        - name: gcloud-secrets
          mountPath: /gcloud-secrets
          readOnly: true
      containers:
      - name: elasticsearch
        env:
        - name: "node.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "node.master"
          value: "false"
        - name: "node.data"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: {{ .Env.ELASTICSEARCH_DATA_JAVA_OPTIONS }}
        image: {{ .Env.ELASTICSEARCH_DOCKER_IMAGE }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: {{ .Env.ELASTICSEARCH_DATA_MEMORY_REQUEST }}G
            cpu: {{ .Env.ELASTICSEARCH_DATA_CORES_REQUEST }}
        ports:
        - containerPort: 9300
          name: transport
        readinessProbe:
          httpGet:
            path: /_cat/master
            port: 9200
          timeoutSeconds: 10
        volumeMounts:
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: es-keystore
          mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
          subPath: elasticsearch.keystore
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      #serviceAccountName: es-operator
      volumes:
        - name: es-data
          emptyDir: {}
        - name: es-keystore
          emptyDir: {}
        - name: es-config
          configMap:
            name: es-master-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - name: gcloud-secrets
          secret:
            secretName: gcloud
