# Master statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-master
  namespace: siren
spec:
  replicas: 3
  serviceName: es-master
  selector:
    matchLabels:
      app: es
      role: master
  template:
    metadata:
      labels:
        app: es
        role: master
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 50Mi
            cpu: 50m
        securityContext:
          privileged: true
      - name: config
        image: busybox
        image: {{ .Env.ELASTICSEARCH_DOCKER_IMAGE }}
        command:
        - "sh"
        - "-c"
        - "elasticsearch-keystore create && elasticsearch-keystore add-file gcs.client.default.credentials_file /gcloud-secrets/account.json && cp config/elasticsearch.keystore /keystore/elasticsearch.keystore && chmod a+rwx /keystore/elasticsearch.keystore"
        resources:
          requests:
            memory: 512Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - name: es-keystore
          mountPath: /keystore
        - name: gcloud-secrets
          mountPath: /gcloud-secrets
          readOnly: true
      containers:
      - name: elasticsearch
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 4Gi
        image: {{ .Env.ELASTICSEARCH_DOCKER_IMAGE }}
        imagePullPolicy: Always
        env:
        - name: "node.name"
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "ES_JAVA_OPTS"
          value: "-Xmx1024m -Xms1024m"
        - name: node.master
          value: "true"
        - name: node.data
          value: "false"
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 20
        ports:
        - containerPort: 9200
          name: rest
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: es-keystore
          mountPath: /usr/share/elasticsearch/config/elasticsearch.keystore
          subPath: elasticsearch.keystore
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-data
          emptyDir: {}
        - name: es-keystore
          emptyDir: {}
        - name: es-config
          configMap:
            name: es-master-config
            items:
              - key: elasticsearch.yml
                path: elasticsearch.yml
        - name: gcloud-secrets
          secret:
            secretName: gcloud
